# Generated by Django 6.0 on 2026-02-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_student_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
