# Generated by Django 6.0 on 2026-02-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_assignment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfees',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentfees',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfees',
            name='receipt_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
