# Generated by Django 6.0 on 2026-02-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_studentfees_description_studentfees_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
